# Use this docker compose file to run the dependencies (database) for local development
version: '3.8'

services:
  db:
    image: postgres:15.3-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sfi-image-upload
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ “CMD-SHELL”, “pg_isready” ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
